telegram:
  token: AAF8Kr1IWozW6etj4pcOYvj6m4ANqxoCago # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  useCustomEmojiFilter: false # Experimental, might break
  replaceAtWithHash: false # Experimental, might break
  replaceExcessiveSpaces: false # Experimental, might break
  removeNewlineSpaces: false # Experimental, might break
discord:
  useNickname: false
  token: MTA0OTQ2NjI5ODkwNTY1NzM0NA.GZAiFV.9ZzQTzkLr6Qry1yEl3oD9ss8iZRl9F81d5l8FI # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: DAC Bridge Bot
    direction: both
    telegram:
      chatId: -1001177274538 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '1052903716765847613' # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: 'hours' # This string must be a valid Moment time format. Example: seconds, minutes, hours, days, weeks, months, years
persistentMessageMap: false
